"""essage=init

Revision ID: 14f9dfdc2655
Revises: 63e955a0ce14
Create Date: 2026-05-15 21:33:49.415977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f9dfdc2655'
down_revision: Union[str, None] = '63e955a0ce14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller_card', sa.Column('banner_image', sa.String(), nullable=True))
    op.add_column('seller_card', sa.Column('avatar_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller_card', 'avatar_image')
    op.drop_column('seller_card', 'banner_image')
    # ### end Alembic commands ###
