"""essage=init

Revision ID: 1e2695dae2fe
Revises: 98ca5cc9d646
Create Date: 2026-04-14 02:13:17.059067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e2695dae2fe'
down_revision: Union[str, None] = '98ca5cc9d646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'seller_card', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seller_card', type_='unique')
    # ### end Alembic commands ###
