"""essage=init

Revision ID: 63e955a0ce14
Revises: ba7219f5033e
Create Date: 2026-05-15 17:53:06.705253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63e955a0ce14'
down_revision: Union[str, None] = 'ba7219f5033e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advert_banner',
    sa.Column('image_uuid', sa.UUID(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advert_banner')
    # ### end Alembic commands ###
