"""essage=init

Revision ID: 98ca5cc9d646
Revises: 3c3d9049c996
Create Date: 2026-04-13 21:02:18.788851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ca5cc9d646'
down_revision: Union[str, None] = '3c3d9049c996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_settings', 'ava_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_settings', 'ava_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
