"""essage=init

Revision ID: d36b4ff05302
Revises: dc649231b173
Create Date: 2026-05-15 07:05:39.615220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36b4ff05302'
down_revision: Union[str, None] = 'dc649231b173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_user_id_fkey'), 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('cart_item_product_id_fkey'), 'cart_item', type_='foreignkey')
    op.drop_constraint(op.f('cart_item_cart_id_fkey'), 'cart_item', type_='foreignkey')
    op.create_foreign_key(None, 'cart_item', 'cart', ['cart_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cart_item', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('inventory_product_id_fkey'), 'inventory', type_='foreignkey')
    op.create_foreign_key(None, 'inventory', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('order_customer_id_fkey'), 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'user', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('order_item_product_id_fkey'), 'order_item', type_='foreignkey')
    op.drop_constraint(op.f('order_item_order_id_fkey'), 'order_item', type_='foreignkey')
    op.create_foreign_key(None, 'order_item', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order_item', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('product_seller_card_id_fkey'), 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'seller_card', ['seller_card_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('product_alternative_alt_product_id_fkey'), 'product_alternative', type_='foreignkey')
    op.drop_constraint(op.f('product_alternative_product_id_fkey'), 'product_alternative', type_='foreignkey')
    op.create_foreign_key(None, 'product_alternative', 'product', ['alt_product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'product_alternative', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.add_column('product_image', sa.Column('image_uuid', sa.UUID(), nullable=False))
    op.add_column('product_image', sa.Column('order', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('product_image_product_id_fkey'), 'product_image', type_='foreignkey')
    op.create_foreign_key(None, 'product_image', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('product_image', 'image_url')
    op.drop_constraint(op.f('product_moderation_moderator_id_fkey'), 'product_moderation', type_='foreignkey')
    op.drop_constraint(op.f('product_moderation_product_id_fkey'), 'product_moderation', type_='foreignkey')
    op.create_foreign_key(None, 'product_moderation', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'product_moderation', 'user', ['moderator_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('review_order_item_id_fkey'), 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'order_item', ['order_item_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('seller_card_user_id_fkey'), 'seller_card', type_='foreignkey')
    op.create_foreign_key(None, 'seller_card', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_settings_user_id_fkey'), 'user_settings', type_='foreignkey')
    op.create_foreign_key(None, 'user_settings', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_settings', type_='foreignkey')
    op.create_foreign_key(op.f('user_settings_user_id_fkey'), 'user_settings', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'seller_card', type_='foreignkey')
    op.create_foreign_key(op.f('seller_card_user_id_fkey'), 'seller_card', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key(op.f('review_order_item_id_fkey'), 'review', 'order_item', ['order_item_id'], ['id'])
    op.drop_constraint(None, 'product_moderation', type_='foreignkey')
    op.drop_constraint(None, 'product_moderation', type_='foreignkey')
    op.create_foreign_key(op.f('product_moderation_product_id_fkey'), 'product_moderation', 'product', ['product_id'], ['id'])
    op.create_foreign_key(op.f('product_moderation_moderator_id_fkey'), 'product_moderation', 'user', ['moderator_id'], ['id'])
    op.add_column('product_image', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_image', type_='foreignkey')
    op.create_foreign_key(op.f('product_image_product_id_fkey'), 'product_image', 'product', ['product_id'], ['id'])
    op.drop_column('product_image', 'order')
    op.drop_column('product_image', 'image_uuid')
    op.drop_constraint(None, 'product_alternative', type_='foreignkey')
    op.drop_constraint(None, 'product_alternative', type_='foreignkey')
    op.create_foreign_key(op.f('product_alternative_product_id_fkey'), 'product_alternative', 'product', ['product_id'], ['id'])
    op.create_foreign_key(op.f('product_alternative_alt_product_id_fkey'), 'product_alternative', 'product', ['alt_product_id'], ['id'])
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(op.f('product_seller_card_id_fkey'), 'product', 'seller_card', ['seller_card_id'], ['id'])
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.create_foreign_key(op.f('order_item_order_id_fkey'), 'order_item', 'order', ['order_id'], ['id'])
    op.create_foreign_key(op.f('order_item_product_id_fkey'), 'order_item', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key(op.f('order_customer_id_fkey'), 'order', 'user', ['customer_id'], ['id'])
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_product_id_fkey'), 'inventory', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'cart_item', type_='foreignkey')
    op.drop_constraint(None, 'cart_item', type_='foreignkey')
    op.create_foreign_key(op.f('cart_item_cart_id_fkey'), 'cart_item', 'cart', ['cart_id'], ['id'])
    op.create_foreign_key(op.f('cart_item_product_id_fkey'), 'cart_item', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key(op.f('cart_user_id_fkey'), 'cart', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
