"""essage=init

Revision ID: dc649231b173
Revises: 1e2695dae2fe
Create Date: 2026-04-14 08:38:11.383361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc649231b173'
down_revision: Union[str, None] = '1e2695dae2fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'total_price')
    op.add_column('product_moderation', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('product_moderation', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('review', sa.Column('order_item_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('review_customer_id_fkey'), 'review', type_='foreignkey')
    op.drop_constraint(op.f('review_product_id_fkey'), 'review', type_='foreignkey')
    op.drop_constraint(op.f('review_order_id_fkey'), 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'order_item', ['order_item_id'], ['id'])
    op.drop_column('review', 'order_id')
    op.drop_column('review', 'customer_id')
    op.drop_column('review', 'product_id')
    op.create_unique_constraint(None, 'user_settings', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_settings', type_='unique')
    op.add_column('review', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('review', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('review', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key(op.f('review_order_id_fkey'), 'review', 'order', ['order_id'], ['id'])
    op.create_foreign_key(op.f('review_product_id_fkey'), 'review', 'product', ['product_id'], ['id'])
    op.create_foreign_key(op.f('review_customer_id_fkey'), 'review', 'user', ['customer_id'], ['id'])
    op.drop_column('review', 'order_item_id')
    op.drop_column('product_moderation', 'updated_at')
    op.drop_column('product_moderation', 'created_at')
    op.add_column('order', sa.Column('total_price', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
